export const FETCH_INIT = 'FETCH_INIT';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_FAILURE = 'FETCH_FAILURE';
export const UPDATE_PAGE_LIMIT = 'UPDATE_PAGE_LIMIT';
export const CHANGE_PAGE_FETCH_CHARACTERS = 'CHANGE_PAGE_FETCH_CHARACTERS';
